name: Build TitleDB
run-name: Building TitleDB! 🚀
on: workflow_dispatch
jobs:
  build_titledb:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: .*linux-x64
          name_is_regexp: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: blawar/titledb
          fetch-depth: 1
      - name: "List"
        run: ls -la
      - name: "Run NSFW"
        run: cd *linux-x64 && chmod +x nsfw && ./nsfw -v
