name: Build TitleDB
run-name: Building TitleDB! 🚀
on: workflow_dispatch
jobs:
  build_titledb:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
      - name: "Run NSFW"
        run: cd *linux-x64 && ./nsfw -v
