name: Build TitleDB
run-name: Building TitleDB! 🚀
on: workflow_dispatch
jobs:
  build_titledb:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow_conclusion: ""
        branch: master
        path: extracted
        workflow: "build.yml"
    - name: List files
      run: ls -la extracted
