name: Build TitleDB
run-name: Building TitleDB! 🚀
on: workflow_dispatch
jobs:
  build_titledb:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: "Download"
      uses: actions/download-artifact@v4
    - name: "List"
      run: ls -al
