name: Build TitleDB
run-name: Building TitleDB! 🚀
on: workflow_dispatch
jobs:
  build_titledb:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: "NSFW-v${{ env.GitVersion_MajorMinorPatch }}-linux-x64"
      - name: "Run NSFW"
        run: ./nsfw -v
